- What are the basic action hooks & filter in the wordpress
- How to create the Ajax Call in the WordPress
- What will be the ajax URL of the ajax call for the front end functionality.
- Where you will add the Ajax call code, in which file you will add it. 
- What is the process of plugin development
- How will you add the name of your plugin in the WordPress plugin.
- How will you print the "Hello Word" using the WordPress plugin. 
- What are the security plugins used in the WordPress.